# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'QminderTVApp' do
  
  pod 'QminderAPI', :path => '../'

  target 'QminderApiTests' do
    pod 'Quick'
    pod 'Nimble'
    pod 'QminderAPI', :path => '../'
  end
end