update_fastlane

default_platform :ios

before_all do
  ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
end

platform :ios do
  desc "Depoy new Swift API version"
  lane :release do
    ensure_git_branch
    version = version_get_podspec(path: "QminderAPI.podspec")
    changelog = prompt(text: "Changelog: ", multi_line_end_keyword: "END")
    github_release = set_github_release(
      repository_name: "Qminder/swift-api",
      api_token: ENV['GITHUB_TOKEN'],
      name: version,
      tag_name: version,
      description: changelog,
      commitish: "master"
    )
    sh("git fetch --tags")
    pod_push(allow_warnings: true, verbose: true)
    slack(
      message: "QminderAPI successfully released!",
      channel: "#apple-dev-ops",
      payload: {
        "Version": version,
        "Changelog": changelog
      }
    )
  end

end
