update_fastlane

default_platform :ios

platform :ios do

  desc "Unit tests"
  lane :test do
    # iOS
    scan(
      project: "QminderAPI.xcodeproj",
      scheme: "QminderAPI-iOS",
      xcargs: "CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO",
      clean: true,
      devices: ["iPhone X"]
    )

    # tvOS
    scan(
      project: "QminderAPI.xcodeproj",
      scheme: "QminderAPI-tvOS",
      xcargs: "CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO",
      clean: true,
      devices: ["Apple TV 4K"]
    )

    # macos
    xcodebuild(
      archive: false,
      project: "QminderAPI.xcodeproj",
      scheme: "QminderAPI-macOS",
      xcargs: "CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO",
      clean: true,
      build: true
    )

    # watchOS
    xcodebuild(
      archive: false,
      project: "QminderAPI.xcodeproj",
      scheme: "QminderAPI-watchOS",
      xcargs: "CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO",
      clean: true,
      build: true
    )
  end

  desc "Depoy new Swift API version"
  lane :release do
    ensure_git_branch
    version = version_get_podspec(path: "QminderAPI.podspec")
    changelog = prompt(text: "Changelog: ", multi_line_end_keyword: "END")
    github_release = set_github_release(
      repository_name: "Qminder/swift-api",
      api_token: ENV['GITHUB_TOKEN'],
      name: version,
      tag_name: version,
      description: changelog,
      commitish: "master"
    )
    sh("git fetch --tags")
    pod_push(allow_warnings: true, verbose: true)

    if ENV["SLACK_URL"]
      slack(
        message: "QminderAPI successfully released!",
        channel: "#apple-dev-ops",
        payload: {
          "Version": version,
          "Changelog": changelog
        }
      )
    end
  end

  desc "Generate documentation"
  lane :generate_docs do
    jazzy(
      config: ".jazzy.yaml"
    )
  end

end
